### ISSUE TITLE
Schools missing staff_degree

### ISSUE THREAD

**Issue by mepps** [DC-OSSE/LearnDC_v2#128]
https://github.com/socialdriver/learndc-data/blob/master/converted/school/0202/staff_degree.json

Hi Ben, the school above has staff_degree in our repo but not in the new one which is causing an error. Can you let me know any schools that don't have staff_degree anymore so I can delete the files on our end and re-run the import?

Thanks!
Maggie

**Comment by benjaminrobinson** [comment]
This might be a little hard to do...can you tell me which schools have staff_degree JSON files on your end and then I can check if they exist on my end?  I can send you a list of school codes that have staff_degree files in our database.

**Comment by mepps** [comment]
@benjaminrobinson I saw this again with 0204.

On our end, all the leas with staff_degree are:

0000, 0001, 0104, 0106, 0108, 0109, 0113, 0114, 0115, 0116, 0117, 0118, 0120, 0121, 0122, 0123, 0124, 0125, 0126, 0127, 0129, 0130, 0132, 0133, 0135, 0137, 0138, 0139, 0140, 0142, 0143, 0144, 0145, 0146, 0147, 0149, 0151, 0152, 0153, 0155, 0156, 0158, 0159, 0160, 0163, 0165, 0166, 0167, 0168, 0169, 0170, 0171

And all the schools are:

 0101, 0102, 0105, 0106, 0109, 0113, 0114, 0115, 0116, 0117, 0121, 0125, 0126, 0127, 0128, 0130, 0131, 0132, 0133, 0134, 0135, 0138, 0140, 0142, 0146, 0151, 0153, 0158, 0159, 0160, 0161, 0163, 0165, 0168, 0169, 0170, 0173, 0174, 0178, 0181, 0182, 0183, 0184, 0186, 0188, 0189, 0190, 0191, 0193, 0195, 0196, 0198, 0199, 0202, 0203, 0204, 0205, 0206, 0210, 0212, 0213, 0217, 0220, 0221, 0222, 0224, 0227, 0231, 0232, 0238, 0239, 0246, 0247, 0249, 0251, 0252, 0254, 0257, 0258, 0259, 0261, 0262, 0264, 0266, 0271, 0272, 0273, 0274, 0280, 0284, 0285, 0287, 0288, 0290, 0291, 0292, 0294, 0295, 0296, 0299, 0300, 0301, 0302, 0305, 0307, 0308, 0309, 0312, 0313, 0315, 0316, 0319, 0321, 0322, 0324, 0325, 0326, 0327, 0328, 0329, 0330, 0332, 0333, 0335, 0336, 0338, 0339, 0344, 0346, 0360, 0361, 0362, 0363, 0364, 0365, 0366, 0370, 0402, 0404, 0405, 0407, 0409, 0413, 0416, 0417, 0421, 0427, 0428, 0433, 0442, 0450, 0452, 0454, 0455, 0456, 0457, 0458, 0459, 0462, 0463, 0464, 0466, 0467, 0474, 0478, 0860, 0861, 0884, 1047, 1100, 1103, 1104, 1105, 1106, 1107, 1108, 1109, 1110, 1113, 1116, 1117, 1118, 1120, 1121, 1122, 1123, 1124, 1125, 1129, 1137, 1138, 1206, 1207, 3064, 3065, 3067, 3068, 3069, 3070, 3071

**Comment by benjaminrobinson** [comment]
@mepps Could you? Email these two lists as comma separated values files?  Thanks!

**Comment by mepps** [comment]
Emailed

**Comment by benjaminrobinson** [comment]
:+1:

**Comment by benjaminrobinson** [comment]
Update.  I was suppressing data that had n sizes of less than ten so a bunch of schools were missing files completely.  Have since been told that that suppression was incorrect so a bunch more schools and LEAs will have those files now.  Will get back to you on this front shortly now that the situation has changed a little bit (not sure if this kind of request with just school and LEA codes and if they have an exhibit is considered "data sharing" or not according to our new process, @gwenrr?)...

**Comment by mepps** [comment]
@benjaminrobinson I found another school with this issue: 0126 (Briya). Should it have a staff_degree exhibit?

**Comment by benjaminrobinson** [comment]
It should not...I made a small commit before the big one where I removed some schools' hqt_classes.json or staff_degree.json files...this is because these schools are special education or adult schools and we are not required to report on them for accountability purposes.  I also made the corresponding changes to the .gitignore file...

https://github.com/DC-OSSE/LearnDC_v2/commit/ef864d4827cac4dccef866f19d27b5d5df0d0d94

**Comment by mepps** [comment]
Hmm, I don't see Briya in the gitignore. I can remove it from our files for now, but let me know if there are others where I should remove them.

**Comment by benjaminrobinson** [comment]
Ah....It might be that they didn't have a staff_degree.JSON file before and I never created one in the new post-appeals aggregation process (i.e. just removed them from ever having the possibility of having a file created).  The others (that I can think of!) that were removed were the adult/special education schools:
- Next Step (0168)
- Carlos Rosario (1119)
- St. Coletta (1047)
- Sharpe Health (0312)
- Mamie D Lee (0265)
