### ISSUE TITLE
Suggestion: Change JSON to expanded format

### ISSUE THREAD

**Issue by psteininger** [DC-OSSE/LearnDC_v2#13]
Currently the JSON files are ad-hoc formatted, with the data portion of the exhibit being spit out on one line. I would suggest "pretty formatting" JSON, so that changes from the previous import are more apparent. Before the data lands in socialdirver/learndc-data we read in the file from DC-OSSE/LearnDCv2 parse the JSON, make alignments/corrections, and then unparse the JSON with pretty formatting. This is how we catch a lot of issues before pushing to github.

**Comment by benjaminrobinson** [comment]
Working on this as part of fixing the "malformed json" issue...

**Comment by benjaminrobinson** [comment]
All JSON files have been "prettified"!

**Comment by benjaminrobinson** [comment]
Thought this was an issue again but it should be re-implemented (correctly, I might add!) across all the JSON files for LearnDC...

**Comment by benjaminrobinson** [comment]
Only set of files that were not "prettified" were the LEA enrollment exhibit files...that was causing a parsing issue that ended up creating a JSON that had no values...Will do some investigating tomorrow about which LEA's file is causing this problem.  This will not delay the release of anything but is just an issue I want to flag so that we can get it right!

**Comment by mepps** [comment]
Great work Ben!!

**Comment by cmgiven** [comment]
Will note that this same file will likely display a JSON parsing error. We'll need to manually fix for the time being.

**Comment by benjaminrobinson** [comment]
Found it!  It was DYRS's LEA enrollment file.  It exists in the school directory but does not exist in the enrollment by LEA.  Therefore subsetting it out of the ETL resolves the issue!
