### ISSUE TITLE
0% HQT showing at NaN%

### ISSUE THREAD

**Issue by gwenrr** [DC-OSSE/LearnDC_v2#138]
![screenshot 2015-04-17 14 24 19](https://cloud.githubusercontent.com/assets/7264714/7208279/973533ae-e50d-11e4-9509-9d88f9d7b95d.png)

Is there a way this could actually say 0% (it's because school / LEA has not reported)

I think this makes the data look like a mistake.

Gwen

**Comment by benjaminrobinson** [comment]
@cmgiven:  The data, specifically in the HQT Classes exhibit has some files that show schools and LEAs that did not report to OSSE for the highly qualified collection at the time for whatever reason.  These schools' data shows 0 num_hq, 0 num_nhq, and 0 num_total yielding the "not a number" response on the website.  I don't think there's any way to change that to a 0 but Gwen and I are worried that LEAs will think there was an error in the data rather than a 0, which could cause some confusion among LEAs.  Worst case scenario is that we tell LEAs that if their HQT exhibit has an "NaN" in the percentage on the staging site, that they are missing data and need to report for that school or provide a reason why that data should not exist for that school in the first place.  Sound good?  Just clarifying!

**Comment by cmgiven** [comment]
Yes. @mepps, if we can add a catch for any school that has a 0 as its num_total to report 0% on the site, that should address this case.

**Comment by mepps** [comment]
![screen shot 2015-04-17 at 3 53 57 pm](https://cloud.githubusercontent.com/assets/4406809/7209792/fef90400-e519-11e4-96f3-b9bd041986a1.png)

Fixed on staging.

**Comment by gwenrr** [comment]
Thanks so much, everyone. Better!
