### ISSUE TITLE
Formatting: Enrollment and Median Growth Percentile on Profile Tab

### ISSUE THREAD

**Issue by mepps** [DC-OSSE/LearnDC_v2#32]
Chris, I'm not seeing the same issues you are on these now. My fix for special education might have fixed it but can you look and point me to a school where you see it?

**Comment by benjaminrobinson** [comment]
Removed the "Grade" subgroups from the MGP exhibit...

**Comment by benjaminrobinson** [comment]
I believe this issue has been dealt with (as far as removing the Grade subgroup keys as well as checking for consistency in the Grade subgroup keys) so I'm going to close it since I'm about 95% confident that I made the subgroup keys consistent across all the LearnDC exhibit files.

**Comment by benjaminrobinson** [comment]
We are still coding Adults Only as "grade AO" and not as "AO"...I see that subgroup still appearing wherever that grade exists in a school.  Did we want to change that to be "AO" and not "grade AO" or is that not an issue?  I don't remember discussing but thought it would be better to be safe than sorry when I ran into it!

**Comment by mepps** [comment]
In our grades I see "grade ao" and "ao", and we now have a subgroup called "ao". Does this answer your question?

**Comment by benjaminrobinson** [comment]
We have the subgroup AO just for Briya, I believe...but did we ever have a preference for AO or grade AO?  Not sure that answers my question.  I guess my question is:  are there instances where we have "grade AO" and other instances where we have "AO" as a key (outside of the Briya instance)?  Because this may have been a key that I did not standardize across the data.  I may be overdoing it on this one since I don't remember it coming up in previous discussions so feel free to let me know if I'm going overboard here!
