### ISSUE TITLE
Front-end: Formatting of MGP labels

### ISSUE THREAD

**Issue by gwenrr** [DC-OSSE/LearnDC_v2#63]
Is this us or you? Here's an example.
![screenshot 2015-01-08 12 33 22](https://cloud.githubusercontent.com/assets/7264714/5667054/a92448a8-9732-11e4-83f6-a548ee9c4d9d.png)

**Comment by cmgiven** [comment]
Us.

**Comment by cmgiven** [comment]
These are also not percentages, and so should not have "%" appended to the end.

**Comment by gwenrr** [comment]
Gosh - thanks for noticing the % issue.

**Comment by mepps** [comment]
I took out the % on stage but it also changes where the line displays. Screen shot attached. Leaving the change live unless I hear otherwise because I think not communicating that the data is a percent when it's not a percent is important but we should discuss at the 2:30 meeting. It may require more extensive code changes, because I think when this was originally written they were thinking of it as a percent.
![screen shot 2015-01-08 at 1 52 41 pm](https://cloud.githubusercontent.com/assets/4406809/5668458/aa48ae4e-973d-11e4-8589-7b8f8fb03202.png)

**Comment by mepps** [comment]
Sorry everyone, I decided not to leave that live until we discuss it, just because I don't want the data to look wrong. I can make the change as soon as we're clear on how it should look.

**Comment by cmgiven** [comment]
Looks like the styles are just using the label value in CSS. So it's interpreting 46 as 46 px?


Chris


—

**Comment by mepps** [comment]
![screen shot 2015-01-12 at 11 56 29 am](https://cloud.githubusercontent.com/assets/4406809/5706849/1738c2c0-9a52-11e4-8f0c-85d4a1a1abd9.png)

Removed percents. Please let me know if there's another change that needs to be made.

**Comment by cmgiven** [comment]
That looks great. Thanks, Maggie.

**Comment by gwenrr** [comment]
Thanks, Chris and Maggie.

**Comment by gwenrr** [comment]
Decimals still showing on MGP exhibit
![new screenshot 2015-01-14 14 31 43](https://cloud.githubusercontent.com/assets/7264714/5745956/57af72be-9bfa-11e4-9005-90d4ebeaaba7.png)

**Comment by mepps** [comment]
![screen shot 2015-01-20 at 9 17 30 am](https://cloud.githubusercontent.com/assets/4406809/5818645/2fca3f1a-a085-11e4-9a6b-0b0cfac90434.png)

Fixed in staging.
