### ISSUE TITLE
Briya PCS (SC = 0126) - Can we break this into two Equity Reports?

### ISSUE THREAD

**Issue by gwenrr** [DC-OSSE/LearnDC_v2#71]
One for the adult enrollment and one for the child enrollment?

What would we need to do to make that happen?

**Comment by cmgiven** [comment]
This is not possible. LearnDC is deeply tied to the notion of one school code to one school profile. This would require extensive reworking at every level in order to make it possible.

If they want two equity reports, they'll need to have two school codes.

**Comment by gwenrr** [comment]
Would I be possible then to have two ISA exhibits - one for adults and one for children?

**Comment by cmgiven** [comment]
Not easily, no. We could manage this by creating an entirely new exhibit just for Briya. But we would not be able to accomplish this on the current timeline.

**Comment by gwenrr** [comment]
OK - we will communicate this to group.

**Comment by gwenrr** [comment]
Or would it be possible to have two separate bars on this exhibit - one for adults and one for children?

**Comment by cmgiven** [comment]
Possibly. What this would require is Ben adding additional subgroups to this school. However, this has ramifications for both the API and the front-end and needs some scrutiny before we can consider adding this late in the game.

@mepps and @psteininger: Would it be possible to add two new subgroups which would only appear in the attendance exhibit? These would perhaps be "Adult Students" and "Juvenile Students."

Gwen, note that this proposed solution would not change the values of the pull-out, the all students bar, or the other subgroup bars.

**Comment by mepps** [comment]
We can add the subgroups, assuming we know what the keys for them will be.

**Comment by benjaminrobinson** [comment]
Chris and I made the changes on my end in the Equity Report aggregator...The ISA exhibit should have a key just for Briya that indicates the Adults Only subgroup or as we have named it for key purposes:  "AO".

**Comment by gwenrr** [comment]
So my fault - PCSB gave us the numbers.

Adult = 72%
PreK = 82%

and the demographic ISA rates should be an aggregate of all students

**Comment by benjaminrobinson** [comment]
For the time being, we will just add this into the SQL database instead of changing the aggregator file as we don't want to wash away/lose any changes that were made to the equity_longitudinal table that exists in our database by writing over that table with a new piece of data.  Adding the Briya line in the database is our best option for now and then making changes to the Equity Report aggregator to use equity_longitudinal as our base table for making changes in the future.  Just wanted this to be out here so that I'm reminded after this whole process is over to make these changes so that updates to the table made in SQL can be easily incorporated without losing previous changes that are most easily made in the database itself.
