### ISSUE TITLE
Formatting: fiscal_year to year in sped_apr

### ISSUE THREAD

**Issue by mepps** [DC-OSSE/LearnDC_v2#97]
Hey Ben, as we develop the sped_apr exhibit, I wanted to point your attention to a change I had to make on my end to the keys. I changed fiscal_year to year so that it is consistent with the rest of the data. Is that an easy change to the etl? This is not urgent, just wanted to point it out.

**Comment by benjaminrobinson** [comment]
It can be changed easily in the ETL, I just want to make sure that the fiscal year is matched to the correct school year but this isn't a big problem to fix at all...thanks for bringing it to my attention!

**Comment by benjaminrobinson** [comment]
@gwenrr Do you know if the fiscal year is the same as a regular year here for the SPED APR?  Fiscal year here is listed as 2012...does that entail the '12-'13 school year and should be changed to 2013 for the year or the '13-'14 school year and 2014?  Or something completely different from what I'm talking about here?

**Comment by benjaminrobinson** [comment]
We might have to come up with a creative solution in the written text on this page @cmgiven since the federal fiscal year does not map onto school years at all!  I can change the variable name to year here but I think explanatory text might be necessary to explain the distinction for the data for this exhibit.
